
CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_number VARCHAR(50) UNIQUE NOT NULL,

    total_amount NUMERIC(12,2) NOT NULL,
    order_status VARCHAR(30) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    quantity INT NOT NULL,
    price NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id),

    CONSTRAINT fk_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
);


CREATE TABLE cart (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    quantity INT NOT NULL,

    CONSTRAINT fk_cart
        FOREIGN KEY (cart_id) REFERENCES cart(cart_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_cart_user_active
ON cart(user_id)
WHERE status = 'ACTIVE';

